pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    // stages {
    //     stage('Checkout') {
    //         steps {
    //             git branch: 'main',
    //                 credentialsId: 'github_creds',
    //                 url: 'https://github.com/yonas-baysasaw/alx-backend-python.git'
    //         }
    //     }

    //     stage('Install Dependencies') {
    //         steps {
    //             sh '''
    //             python3 -m venv $VENV_DIR
    //             source $VENV_DIR/bin/activate
    //             pip install -r requirements.txt pytest pytest-html
    //             '''
    //         }
    //     }

    //     stage('Run Tests') {
    //         steps {
    //             sh '''
    //             source $VENV_DIR/bin/activate
    //             pytest --html=report.html --self-contained-html
    //             '''
    //         }
    //     }

    //     stage('Publish Report') {
    //         steps {
    //             publishHTML([allowMissing: false,
    //                 alwaysLinkToLastBuild: true,
    //                 keepAll: true,
    //                 reportDir: '.',
    //                 reportFiles: 'report.html',
    //                 reportName: 'Test Report'])
    //         }
    //     }
    // }
    stages{
        stage("build"){
            steps{
                echo 'building the application ...'
            }
        }
        stage("test"){
            steps{
                echo 'testing the application ...'
            }
        }
        stage("deploy"){
            steps{
                echo 'deploying the application ...'
            }
        }
    }

    // triggers {
    //     // Manual trigger only — no automatic build
    // }
}