pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github_creds',
                    url: 'https://github.com/yonas-baysasaw/alx-backend-python.git'
            }
        }

stage('Install Dependencies') {
    steps {
        bat 'python -m venv venv'
        bat 'call venv\\Scripts\\activate.bat && pip install -r messaging_app\\requirements.txt'
    }
}


// stage('Run Tests') {
//     steps {
//         bat """
//         call %VENV_DIR%\\Scripts\\activate.bat
//         pytest --html=report.html --self-contained-html
//         """
//     }
// }


//         stage('Publish Report') {
//             steps {
//                 publishHTML(target: [
//                     reportDir: '.',
//                     reportFiles: 'report.html',
//                     reportName: 'Test Report',
//                     allowMissing: false,
//                     alwaysLinkToLastBuild: true,
//                     keepAll: true
//                 ])
//             }
//         }
  stage('Run Tests') {
            steps {
                sh '. venv/bin/activate && pytest tests --junitxml=report.xml'
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
    }

}