pipeline {
    agent {
        docker {
            image 'python:3.10'
            args '-u root:root'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/yonas-baysasaw/alx-backend-python.git',
                    branch: 'main',
                    credentialsId: 'github-creds'
                )
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                pip install --upgrade pip
                pip install -r messaging_app/requirements.txt pytest pytest-html
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                pytest messaging_app/tests --html=report.html --self-contained-html
                '''
            }
            post {
                always {
                    archiveArtifacts artifacts: 'report.html', fingerprint: true
                }
            }
        }
    }
}
